### ISSUE TITLE
splits je code op

### ISSUE THREAD

**Issue by raoulg** [joppe2001/visualizations#3]
zie https://github.com/raoulg/MADS-DAV/blob/main/references/codestyle/encapsulation.md

en

https://github.com/raoulg/MADS-DAV/blob/main/references/codestyle/open_closed.md

**Comment by joppe2001** [comment]
Created a base_plotter.py file where i define all the base plots that i will be using throughout the project

Inside of the files i have now made sure that the function that will be ran at the end will not be responsible for too many things and thus have split of the function over multiple chunks of processes

I have tried my best to make it as clean and readable as possible
