### ISSUE TITLE
voeg een duidelijke pipeline toe

### ISSUE THREAD

**Issue by raoulg** [joppe2001/visualizations#5]
Het is nu onduidelijk hoe ik jouw code samenhangend run.
Ik wil graag reproduceerbare resultaten; dus ik wil idealiter een commando hebben, dat ik kan runnen, en dat alles doet wat jij wilt dat er gebeurt;

inladen data
preprocessen
opschonen
visualiseren
visualisaties opslaan
logging
etc

**Comment by joppe2001** [comment]
right now i have the basic analyzer command and the python main.py visualize --all
